# Generated by Django 5.2.17 on 2026-09-14 02:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_place_alter_experience_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_year', 'institution'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_year__isnull', True), ('end_year__gte', models.F('start_year')), _connector='OR'), name='education_end_year_gte_start')],
            },
        ),
    ]
